apiVersion: apps/v1
kind: Deployment                                          
metadata:
  name: todos-backend
spec:
  replicas: 2                                             
  selector:
    matchLabels:
      app: todos-backend
  template:                                               
    metadata:
      labels:
        app: todos-backend                                  
    spec:
      containers:
        - image: pavelvasnetsov/todos-backend
          imagePullPolicy: Always                         
          name: todos-backend
          ports:
            - containerPort: 7000
          envFrom:
            - configMapRef:
                name: backend-config