apiVersion: v1
kind: Service              
metadata:
  name: todos-backend-lb
spec:
  type: LoadBalancer       
  ports:
  - port: 7000               
    protocol: TCP          
    targetPort: 7000         
  selector:                
    app: todos-backend     