apiVersion: apps/v1
kind: Deployment                                          
metadata:
  name: todos-frontend
spec:
  replicas: 2                                             
  selector:
    matchLabels:
      app: todos-frontend
  template:                                               
    metadata:
      labels:
        app: todos-frontend                                  
    spec:
      containers:
        - image: pavelvasnetsov/todos-frontend
          imagePullPolicy: Always                         
          name: todos-frontend
          ports:
            - containerPort: 80